{% set version="2.7.3" %}
package:
  name: arvados-cwl-runner
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arvados-cwl-runner/arvados-cwl-runner-{{ version }}.tar.gz
  sha256: 79fbd35d9d9867385b3e0507067fcaec71572af2dcf393df80a97d5f26e12765

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage("arvados-cwl-runner", max_pin="x.x") }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - ruamel.yaml >=0.15.54
    - cwltool >=3.1
    - schema-salad >=3.0.20181129082112
    - arvados-python-client >=2.6

test:
  imports:
    - arvados_cwl

about:
  home: https://github.com/curoverse/arvados/tree/master/sdk/cwl
  license: Apache 2.0
  summary: 'Arvados Common Workflow Language runner'
