{% set name = "perl-html-parser" %}
{% set version = "3.82" %}
{% set sha256 = "5b1f20dd0e471a049c13a53d0fcd0442f58518889180536c6f337112c9a430d8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTML-Parser-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('perl-html-parser', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-html-tagset
    - perl-test-simple
    - perl-uri
    - perl-http-message
  run:
    - perl
    - perl-html-tagset
    - perl-uri
    - perl-http-message

test:
  imports:
    - HTML::Filter
    - HTML::Parser

about:
  home: "https://metacpan.org/pod/HTML::Parser"
  license: perl_5
  summary: 'HTML parser class'
  doc_url: "https://metacpan.org/pod/HTML::Parser"

extra:
  additional-platforms:
    - linux-aarch64
