{% set name = "perl-datetime-timezone" %}
{% set version = "2.56" %}
{% set sha256 = "a0c882ec6258d8c6764211865e3f7cd53862e4851664ac85b09ae6f293c982c5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-TimeZone-2.56.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-app-cpanminus
    - perl-module-runtime
    - perl-test-requires
    - perl-test-more
    - perl-test-fatal
    - perl-namespace-autoclean
    - perl-specio
    - perl-extutils-makemaker
    - perl-try-tiny
    - perl-params-validationcompiler

  run:
    - perl
    - perl-app-cpanminus
    - perl-module-runtime
    - perl-namespace-autoclean
    - perl-specio
    - perl-try-tiny
    - perl-params-validationcompiler

test:
  commands:
    - perl -e "use DateTime::TimeZone"

about:
  home: http://metacpan.org/release/DateTime-TimeZone
  license: perl_5
  summary: 'Time zone object base class and factory'
