{% set version = "3.2.1" %}
{% set url = "https://github.com/refresh-bio/KMC/releases/download/v3.2.1/KMC3.2.1.linux.tar.gz" %}  # [linux]
{% set sha256 = "505701c4627bee7c28e8a43290e2aaf91715f203f925d1492ee8f376453235e7" %}  # [linux]
{% set url = "https://github.com/refresh-bio/kmc/releases/download/v3.2.1/KMC3.2.1.mac.tar.gz" %}  # [osx]
{% set sha256 = "d4bd30d5e16bcbaac7f979f18e49e7447b0148709fb26f754490be9e3e766e73" %}  # [osx]

package:
  name: kmc
  version: {{ version }}

source:
  url: {{ url }}
  sha256:  {{ sha256 }}

build:
  number: 4
  run_exports:
    - {{ pin_subpackage("kmc", max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - bzip2
  run:
    - zlib
    - bzip2

test:
  commands:
    - kmc --help

about:
  home: https://github.com/refresh-bio/kmc
  summary: "Tools for efficient k-mer counting and filtering of reads based on k-mer content."
  description: |
    KMC is a utility designed for counting k-mers (sequences
    of consecutive k symbols) in a set of DNA sequences. KMC tools allow performing various operations on k-mers sets.
  license: GPL-3
  license_family: GPL3
  license_file: gpl-3.0.txt
  dev_url: https://github.com/refresh-bio/kmc
