{% set name = "perl-dbd-mysql" %}
{% set version = "5.006" %}
{% set sha256 = "4ca6c6415552a8acd3d8e01a96d0ac5a4a936e845c4c0e6a7ac6a10ad3798db7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-5.006.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-time-hires
    - perl-test-simple
    - perl-dbi
    - perl-test-deep
    - perl-data-dumper
    - perl-extutils-makemaker
    - mysql-connector-cpp
    - perl-devel-checklib >=1.09
  run:
    - perl
    - perl-dbi
    - mysql-connector-cpp

test:
  imports:
    - DBD::mysql

about:
  home: http://dbi.perl.org/
  license: perl_5
  summary: 'A MySQL driver for the Perl5 Database Interface (DBI)'

extra:
  identifiers:
    - biotools:dbd
    - doi:10.1093/nar/gkm964
