name: PR to Bulk branch
on:
  pull_request:
    branches:
      - bulk
    types: [opened, synchronize, reopened]

concurrency:
  group: build-${{ github.event.pull_request.number || github.head_ref }}
  cancel-in-progress: true

jobs:
  build_and_test-osx:
    name: Bulk PR OSX
    runs-on: macos-13 # amd64
    strategy:
      fail-fast: true
      max-parallel: 13
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set path
        run: echo "/opt/mambaforge/bin" >> $GITHUB_PATH

      - name: Fetch conda install script
        run: |
          wget https://raw.githubusercontent.com/bioconda/bioconda-common/bulk/{common,install-and-set-up-conda,configure-conda}.sh

      - name: Set up bioconda-utils
        run: bash install-and-set-up-conda.sh

      - name: Configure conda
        run: bash configure-conda.sh

      - name: Build and Test
        env:
          # Mimic circleci
          OSTYPE: "darwin"
          CI: "true"
        run: |
          set -e
          eval "$(conda shell.bash hook)"
          conda activate bioconda

          # Clean up lingering build artifacts
          rm -f /opt/mambaforge/envs/bioconda/conda-bld/osx-64/*.tar.bz2

          # The SDK isn't actually cached, so reinstall it
          run_conda_forge_build_setup

          if [ -z "$GITHUB_BASE_REF" ] ; then
              export GITHUB_BASE_REF="bulk"
          fi
          git fetch origin "$GITHUB_BASE_REF"

          bioconda-utils build recipes config.yml \
            --lint \
            --git-range origin/"$GITHUB_BASE_REF" HEAD

      - name: Prepare artifacts
        run: |
              (
              rm -rf /tmp/artifacts
              mkdir -p /tmp/artifacts/packages
              cd /opt/mambaforge/envs/bioconda/conda-bld || exit 0
              find -name .cache | xargs rm -rf || true
              for n in index.html channeldata.json osx-64 noarch; do
                cp -rv $n /tmp/artifacts/packages || true
              done
              ) || true

      - name: Archive packages
        uses: actions/upload-artifact@v4
        with:
          name: osx-64-packages
          path: |
            /tmp/artifacts